#配置编码
spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.36.62:3306/theOlds?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&rewriteBatchedStatements=true
#    username: debian-sys-maint
#    password: onR8ei1BQ6yg7FfE
    username: root
    password: root
#配置端口
server:
  port: 8080
  servlet:
    context-path: /theOldsWeb
logging:
  level:
    com.theoldsweb.myweb.web.mapper: debug